[project]
name = "AdaptiveFuzz-Server"
version = "0.1.0"
description = "LLM-Based Adaptive Fuzzing for Vulnerability Discovery"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]

[tool.uv.workspace]
members = [
    "http",
]
